title: Godwin Etim Akpan
description: Data Analytics • Data Engineering • Enterprise GIS • GeoAI • Machine Learning
theme: jekyll-theme-cayman
github_button_label: Explore My Portfolio

markdown: kramdown
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
