title: Godwin Etim Akpan
description: Data Analytics, Data Engineering, Enterprise GIS, GeoAI, and AI-Driven Decision Support
theme: jekyll-theme-cayman

markdown: kramdown
plugins:
  - jekyll-relative-links
